apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

images:
- name: app
  newName: w3ll1n9t0n/app:/home/runner/work/_temp/7d25d5e9-05d3-40b4-b850-8413c93791be.shd4dde5
