apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

images:
- name: app
  newName: w3ll1n9t0n/app
  newTag: 85d3b79bb6ab28a5e0ca7fdfd9f5338569fd9e93
