name: Build e Upload para Docker Hub
on:
  push:
    branches:
      - main

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v2

      - name: Login no Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Obter SHA do commit
        id: commit_sha
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: Build da imagem Docker
        run: |
          docker build -t w3ll1n9t0n/app:${{ steps.commit_sha.outputs.sha_short }} .
          docker tag w3ll1n9t0n/app:${{ steps.commit_sha.outputs.sha_short }} w3ll1n9t0n/app:latest

      - name: Push da imagem para o Docker Hub
        run: |
          docker push w3ll1n9t0n/app:${{ steps.commit_sha.outputs.sha_short }}

      - name: Setup Kustomize
        uses: imranismail/setup-kustomize@v3.6.1

      - name: Atualizar imagem no manifesto Kubernetes
        run: |
          kustomize edit set image w3ll1n9t0n/app:${{ steps.commit_sha.outputs.sha_short }}=w3ll1n9t0n/app:${{ steps.commit_sha.outputs.sha_short }}
          kustomize build k8s | kubectl apply -f -

