name: Build and Upload to Docker Hub
on:
  push:
    branches:
      - main

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get commit SHA
        id: commit_sha
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: Build Docker image
        run: |
          docker build -t w3ll1n9t0n/app:${{ steps.commit_sha.outputs.sha_short }} .
          docker tag w3ll1n9t0n/app:${{ steps.commit_sha.outputs.sha_short }} w3ll1n9t0n/app:latest

      - name: Push image to Docker Hub
        run: |
          docker push w3ll1n9t0n/app:${{ steps.commit_sha.outputs.sha_short }}

      - name: Setup Kustomize
        uses: imranismail/setup-kustomize@v1
        with:
          kustomize-version: "3.6.1"

      - name: Edit Kustomize image tag
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        run: |
          cd k8s
          kustomize edit set image DOCKERHUB_USERNAME/app:${{ steps.commit_sha.outputs.sha_short }}
